name: Build and test

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: insper-embarcados/pico-build@v0
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build/

  test-exe:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        test: [exe1, exe2, exe3, exe4]

    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - uses: insper-embarcados/actions-wokwi-test@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          test_name: ${{ matrix.test }}
