name: Build and test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: insper-embarcados/pico-build@v0
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build/

  test-exe1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest toml

      - name: Install wokwi-cli
        run: |
          wget -q -O /usr/local/bin/wokwi-cli https://github.com/rafaelcorsi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x /usr/local/bin/wokwi-cli

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Run test
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run:
          pytest test.py -ks exe1

  test-exe2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - uses: insper-embarcados/actions-wokwi-test@v5
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          test_name: exe2
